### ISSUE TITLE
Different signal for each QmlObject instance

### ISSUE THREAD

**Issue by SafaAlfulaij** [Staphylo/smoverlay#1]
Hello!
I was searching for a way to create PyQt properties with the least amount of code.
I found [this](https://stackoverflow.com/questions/48425316/how-to-create-pyqt-properties-dynamically?rq=1) but it has a problem that any new instance overwrite all the properties data.
Which I believe is the same as:

https://github.com/Staphylo/smoverlay/blob/b247be89503f2ceb026b71abc6e526296543e0f9/smoverlay/gui/qmlobject.py#L61

Sorry for asking this out of the blue, but is there any solution/workaround to that?

You have my thanks!

**Comment by Staphylo** [comment]
Hi there!

I remember spending quite some time trying to minimize the boilerplate to create shared types between qml and python. However I'm not sure I will have an answer for you since I'm a bit rusty on all the qt+qml+python intricacies.

What I can say though is that the code of this repo doesn't have any problem instantiating multiple object of the same type. Each can have their own attributes without overriding the ones of other instances.

Regarding the signal I can't recall why I put this comment here. Either it's real or it can be a leftover of an old issue. From a quick look in pdb it seems each instance has its own set of pyqtSignal (addresses of objects are different accross instances).

I guess one way to know would be to create two instances of a same object, triggering the signal of one and seeing if only one instance react or both.
Sorry I can't be more helpful than that.

**Comment by SafaAlfulaij** [comment]
Sorry! I thought that the same issue is there.
Things are working now comparing to the link I posted! :D

Thank you really. I appriacte your help and your work!
